#!/bin/bash
#
# pop-up calendar for dzen
#
# based on (c) 2007, by Robert Manea
# http://dzen.geekmode.org/dwiki/doku.php?id=dzen:calendar
# modified by urukrama
# 
# #DE8834
# sed 's/\<[0-9]\>/0&/' ./infile

KILLRESULT=$(ps aux |grep 'dzen2' |wc -l)
echo $KILLRESULT
if [ $KILLRESULT -gt 1 ]; then killall dzen2 && exit; fi

# show time
date +"%H:%M" |dzen2 -fg '#6c6c6c' -bg '#222222' -fn 'Bitstream Vera Sans Mono-20' -x 1630 -y 1010 -w 260 -l 18 -sa c


TODAY=$(expr `date +'%d'` + 0)
MONTH=`date +'%m'`
YEAR=`date +'%Y'`

(
echo '^bg(#222222)^fg(#00EE00)'`date +'[ %A - %H:%M ]'`; echo
\
# current month, hilight header and today
cal \
    | sed -re "s/^(.*[A-Za-z][A-Za-z]*.*)$/^fg(#00EE00)^bg(#222222)\1/;s/(^|[ ])($TODAY)($|[ ])/\1^bg(#00EE00)^fg(#222222)\2^fg(#6c6c6c)^bg(#222222)\3/"

# next month, hilight header
[ $MONTH -eq 12 ] && YEAR=`expr $YEAR + 1`
cal `expr \( $MONTH + 1 \) % 12` $YEAR \
    | sed -e 's/^\(.*[A-Za-z][A-Za-z]*.*\)$/^fg(#00EE00)^bg(#222222)\1/'

) \
    | dzen2 -fg '#6c6c6c' -bg '#222222' -fn 'Bitstream Vera Sans Mono-12' -x 1630 -y 1010 -w 260 -l 18 -sa c -p -e 'onstart=uncollapse;key_Escape=ungrabkeys,exit'

