#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all

Mod=Mod1

hc keybind $Mod-Shift-q quit

hc keybind $Mod-Shift-r reload

hc keybind $Mod-q close

hc keybind $Mod-Return spawn "${TERMINAL:-alacritty}"

hc keybind $Mod-e spawn ~/.config/eww/launch

hc keybind F86AudioRaiseVolume spawn pamixer -i '5'
hc keybind F86AudioRaiseVolume spawn pamixer -i '5'
hc keybind F86AudioMute spawn pamixer -t

hc keybind F86AudioNext spawn playerctl next
hc keybind F86AudioPrev spawn playerctl previous
hc keybind F86AudioPlay spawn playerctl play-pause

hc keybind Print spawn "screenshot'"

hc keybind $Mod-d spawn rofi -show drun

hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right

hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right

hc keybind $Mod-u split bottom 0.5
hc keybind $Mod-o split right 0.5

hc keybind $Mod-Control-space split explode

resizestep=0.02
hc keybind $Mod-Control-h resize left +$resizestep
hc keybind $Mod-Control-j resize down +$resizestep
hc keybind $Mod-Control-k resize up +$resizestep
hc keybind $Mod-Control-l resize right +$resizestep

hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma use_index -1 --skip-visible

hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-f set_attr clients.focus.floating toggle
hc keybind $Mod-Shift-m set_attr clients.focus.minimized true
hc keybind $Mod-Control-m jump_to last-minimized
hc keybind $Mod-p pseudotile toggle

hc keybind $Mod-space \
    or , and . compare tags.focus.curframe_wcount = 2 \
    . cycle_layout +1 vertical horizontal max vertical grid \
    , cycle_layout +1

hc mousebind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

hc keybind $Mod-Backspace   cycle_monitor
hc keybind $Mod-Tab         cycle_all +1
hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c      cycle
hc keybind $Mod-i      jump_to urgent

tag_names=( {0..9} )
# tag_keys=( plus, bracketleft, braceleft, parenleft, ampersand, equal, parenright, braceright, bracketright, asterisk )

# hc rename default "'${tag_names[0]}" || true
# # Automatically assigns Mod-{1..9} keys for screens
# # Doesn't work for real-prog-dvorak layout
# for i in "${!tag_names[@]}" ; do
#     hc add "${tag_names[$i]}"
#     key="${!tag_names[$i]}"
#     if ! [ -z "$key" ] ; then
#         hc keybind "$Mod-$key" use_index "$i"
#         hc keybind "$Mod-Shift-$key" move_index "$i"
#     fi
# done


for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${!tag_names[$i]}"
done

hc keybind "$Mod-plus" use_index "0"
hc keybind "$Mod-Shift-plus" move_index "0"

hc keybind "$Mod-bracketleft" use_index "1"
hc keybind "$Mod-Shift-bracketleft" move_index "1"

hc keybind "$Mod-braceleft" use_index "2"
hc keybind "$Mod-Shift-braceleft" move_index "2"

hc keybind "$Mod-parenleft" use_index "3"
hc keybind "$Mod-Shift-parenleft" move_index "3"

hc keybind "$Mod-ampersand" use_index "4"
hc keybind "$Mod-Shift-ampersand" move_index "4"

hc keybind "$Mod-equal" use_index "5"
hc keybind "$Mod-Shift-equal" move_index "5"

hc keybind "$Mod-parenright" use_index "6"
hc keybind "$Mod-Shift-parenright" move_index "6"

hc keybind "$Mod-braceright" use_index "7"
hc keybind "$Mod-Shift-braceright" move_index "7"

hc keybind "$Mod-bracketright" use_index "8"
hc keybind "$Mod-Shift-bracketright" move_index "8"

hc keybind "$Mod-asterisk" use_index "9"
hc keybind "$Mod-Shift-asterisk" move_index "9"
