#!/bin/bash

hc() {
    herbstclient "$@"
}

# theme
hc attr theme.tiling.reset 1
hc attr theme.floating.reset 1
hc set frame_border_active_color '#222222aa'
hc set frame_border_normal_color '#1010100'
hc set frame_bg_normal_color '#23232300'
hc set frame_bg_active_color '#23232300'
hc set frame_border_width 0
hc set always_show_frame off
hc set frame_bg_transparent on
hc set frame_transparent_width 0
hc set frame_gap 33

hc attr theme.title_height 0
hc attr theme.padding_top 30
hc attr theme.active.color '#eeeeee'
hc attr theme.title.color '#ffffff'
hc attr theme.title_color '#ffffff'
hc attr theme.normal.color '#dadada'
hc attr theme.urgent.color '#7811a1dd'
hc attr theme.normal.title_color '#898989'
hc attr theme.inner_width 0
hc attr theme.inner_color black
hc attr theme.border_width 0
hc attr theme.floating.border_width 0
# hc attr theme.floating.padding_top 20
hc attr theme.floating.outer_width 0
hc attr theme.floating.outer_color black
hc attr theme.active.inner_color '#789161'
hc attr theme.urgent.inner_color '#9a65b0'
hc attr theme.normal.inner_color '#606060'
# hc attr theme.active.outer_color '#9a65b0'
for state in active urgent normal ; do
    hc substitute C theme.${state}.inner_color \
        attr theme.${state}.outer_color C
done
hc accr theme.active.outer_width 0
hc attr theme.background_color '#14141400'

hc set window_gap 10
hc set frame_padding 0
hc set smart_window_surroundings off
hc set smart_frame_surroundings off
hc set mouse_recenter_gap 0
