return {
	-- "miversen33/import.nvim",
	-- "lewis6991/impatient.nvim",
	-- "wbthomason/packer.nvim",
	-- "glepnir/lspsaga.nvim", -- LSP UIs
	-- "neovim/nvim-lspconfig", -- LSP
	-- "williamboman/mason.nvim",
	-- "williamboman/mason-lspconfig.nvim",
	-- "MunifTanjim/prettier.nvim", -- Prettier plugin for builtin Neovim lsp
	-- "MunifTanjim/eslint.nvim",
	-- "neoclide/vim-jsx-improve",
	-- "hrsh7th/cmp-buffer", -- nvim-cmp source for buffer words
	-- "hrsh7th/cmp-nvim-lsp", -- nvim-cmp source for neovim's builtin lsp
	-- "hrsh7th/nvim-cmp", -- Completion
	-- "jose-elias-alvarez/null-ls.nvim", -- Use neovim as language server to inject lsp diagnostics, code actions and more
	-- "jayp0521/mason-null-ls.nvim",
	-- { "tzachar/cmp-tabnine", build = "./install.sh", dependencies = "hrsh7th/nvim-cmp" },
	-- "L3MON4D3/Luasnip", -- Snippets
	-- "nvim-treesitter/nvim-treesitter",
	-- "nvim-treesitter/playground",
	-- "RRethy/nvim-treesitter-textsubjects",
	-- "windwp/nvim-autopairs",
	-- "windwp/nvim-ts-autotag",
	-- "lewis6991/gitsigns.nvim",
	-- "norcalli/nvim-colorizer.lua",
	-- "vigoux/notifier.nvim",
	-- "nvim-lua/plenary.nvim", -- common utilities
	-- "nvim-telescope/telescope.nvim",
	-- "nvim-telescope/telescope-file-browser.nvim",
	-- "dinhhuy258/git.nvim", -- for git blame & browse
	-- "sindrets/diffview.nvim",
	-- "onsails/lspkind-nvim", -- vscode-like pictograms
	-- "lukas-reineke/indent-blankline.nvim",
	-- "NMAC427/guess-indent.nvim",
	-- "sindrets/winshift.nvim",
	-- "anuvyklack/middleclass",
	-- "anuvyklack/animation.nvim",
	-- "folke/tokyonight.nvim",
	-- "folke/todo-comments.nvim",
	-- "olivercederborg/poimandres.nvim",
	-- "B4mbus/oxocarbon-lua.nvim",
	-- "Yazeed1s/oh-lucy.nvim",
	-- "shaunsingh/solarized.nvim",
	-- "ellisonleao/gruvbox.nvim",
	-- { "catppuccin/nvim", name = "catppuccin" },
	-- "akinsho/nvim-bufferline.lua",
	-- "tiagovla/scope.nvim",
	-- "moll/vim-bbye",
	-- "kazhala/close-buffers.nvim",
	-- "kyazdani42/nvim-web-devicons",
	-- "tpope/vim-commentary",
	-- "tpope/vim-abolish",
	-- "tpope/vim-fugitive",
	-- "tpope/vim-rhubarb",
	-- "tpope/vim-dispatch",
	-- "tpope/vim-projectionist",
	-- "tpope/vim-dadbod",
	-- "tpope/vim-surround",
	-- "wellle/targets.vim",
	-- "AckslD/nvim-trevJ.lua",
	-- "AndrewRadev/dsf.vim",
	-- "kyazdani42/nvim-tree.lua",
	-- "simrat39/symbols-outline.nvim",
	-- "ray-x/lsp_signature.nvim",
	-- "petertriho/nvim-scrollbar",
	-- "nacro90/numb.nvim",
	-- "arithran/vim-delete-hidden-buffers",
	-- "eandrju/cellular-automaton.nvim",
	-- "mizlan/iswap.nvim",
	-- "superhawk610/ascii-blocks.nvim",
	-- "potamides/pantran.nvim",
	-- "axkirillov/easypick.nvim",
	-- "phaazon/mind.nvim",
	-- "ziontee113/color-picker.nvim",
	-- "bennypowers/nvim-regexplainer",
	-- "andythigpen/nvim-coverage",
	-- "edluffy/specs.nvim",
	-- "joerdav/floobits-neovim",
	-- "aduros/ai.vim",
	-- "chrisgrieser/nvim-various-textobjs",
	-- {
	-- 	"folke/noice.nvim",
	-- 	event = "VimEnter",
	-- 	dependencies = {
	-- 		-- if you lazy-load any plugin below, make sure to add proper `module="..."` entries
	-- 		"MunifTanjim/nui.nvim",
	-- 		-- OPTIONAL:
	-- 		--   `nvim-notify` is only needed, if you want to use the notification view.
	-- 		--   If not available, we use `mini` as the fallback
	-- 		"rcarriga/nvim-notify",
	-- 	},
	-- },
	-- "nvim-lualine/lualine.nvim",
	-- {
	-- 	"anuvyklack/windows.nvim",
	-- 	dependencies = {
	-- 		"anuvyklack/middleclass",
	-- 		"anuvyklack/animation.nvim",
	-- 	},
	-- },
}
